### ISSUE TITLE
Change Brewing Bot to realistic transaction type

### ISSUE THREAD

**Issue by makwarth** [elastic/opbeans#11]
For demos, would it be possible to rename “Brewing Bot” to something more useful / real, like “Queue” or “Batch jobs” or something like that?

**Comment by watson** [comment]
Now the custom transaction type is called "Worker":

![image](https://user-images.githubusercontent.com/10602/36495490-abfd3dce-1735-11e8-8875-abcde68b3602.png)

Each type also have a few relevant fake spans:

![image](https://user-images.githubusercontent.com/10602/36495514-c633f03e-1735-11e8-9bb2-ea1b591afbaf.png)
