### ISSUE TITLE
Add random user type transactions and errors

### ISSUE THREAD

**Issue by makwarth** [elastic/opbeans#12]
For demos, it would be nice to show off this feature.

**Comment by watson** [comment]
`request` transactions and errors now have an associated user:

![image](https://user-images.githubusercontent.com/10602/36495546-ee3be0d2-1735-11e8-8ade-dd278bfd8619.png)

**Comment by watson** [comment]
I also added some custom context:

![image](https://user-images.githubusercontent.com/10602/36495582-0685c450-1736-11e8-9e03-0197325f427a.png)
